# Generated by Django 5.2.1 on 2025-06-20 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='authon',
            new_name='author',
        ),
    ]
