# Generated by Django 5.2.1 on 2025-07-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0005_alter_recipe_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="preparation_time",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="servings",
            field=models.PositiveIntegerField(),
        ),
    ]
